### ISSUE TITLE
How to get high performance reading from GPU

### ISSUE THREAD

**Issue by VarunMohan** [ska-sa/vkgdr#8]
@bmerry Do you think it would be possible to not only get good performance writing from CPU -> GPU but also reading from GPU -> CPU. From what we've benchmarked, it seems like the reads happen a lot more slowly using this approach.

Happy to discuss in more detail if you are available.

**Comment by bmerry** [comment]
I suspect it's not possible. vkgdr is subject to the same hardware limitations as [gdrcopy](https://github.com/NVIDIA/gdrcopy/), whose documentation says:

> Slow D-H, because the GPU BAR, which backs the mappings, can't be prefetched and so burst reads transactions are not generated through PCIE

Possibly reading in larger chunks (e.g. using AVX-512 instructions if available) will help, but that's just a guess.

**Comment by VarunMohan** [comment]
Have you tried this before? We are able to get good performance on the H->D side but after trying stuff can't get good performance on D->H.

We have tried this repository and are thankful that you wrote it! Would you be open to a short call - I'd love to talk through what we've tried and get some advice on if it makes sense.

**Comment by bmerry** [comment]
I haven't tried this before.
